# https://github.com/crytic/echidna/blob/master/tests/solidity/basic/default.yaml

testMode: 'property'
testLimit: 50000
cryticArgs:
  [
    '--solc-remaps',
    '"ds-test/=lib/forge-std/lib/ds-test/src/ @forge-std/=lib/forge-std/src/ contracts/=src/ tests/=test/"',
  ]
